apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pbb6la7hn-dotnet-basic
  janus-idp.io/tekton: pbb6la7hn-dotnet-basic
  backstage.io/kubernetes-id: pbb6la7hn-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pbb6la7hn-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
